### ISSUE TITLE
PromiseKit-SwifterSwift_Privacy conflict with SwifterSwift-SwifterSwift_Privacy

### ISSUE THREAD

**Issue by KavinKily** [mxcl/PromiseKit#1349]
xcode 15.4 
when archive the project will show the error
Showing All Messages
Target 'PromiseKit-SwifterSwift_Privacy' (project 'Pods') has create directory command with output '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-bwmyfxhhjhmwbkbgrjpgazkmrkoo/Build/Intermediates.noindex/ArchiveIntermediates/xxx/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwifterSwift_Privacy.bundle'

Showing All Messages
Target 'SwifterSwift-SwifterSwift_Privacy' (project 'Pods') has create directory command with output '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-bwmyfxhhjhmwbkbgrjpgazkmrkoo/Build/Intermediates.noindex/ArchiveIntermediates/xxx/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwifterSwift_Privacy.bundle'

and when search the key workds SwifterSwift_Privacy.bundle in  pods TARGETS PromiseKit-SwifterSwift_Privacy will show the result 
![image](https://github.com/user-attachments/assets/cd41598a-ee7c-4024-bec3-0fecd449b74f)

**Comment by jiangyewen** [comment]
fixed in this PR https://github.com/mxcl/PromiseKit/pull/1350

**Comment by akovalov** [comment]
Try to add dependency via SPM, not via CocoaPods. In our case, SwifterSwift and other SDK that used SwifterSwift were both via CocoaPods. Moving SwifterSwift to SPM resolved the issue.

**Comment by MJ-BEN** [comment]
Version 8.1.2 still cannot solve this problem. In my project, both SwifterSwift and PromiseKit are used. When executing packaging, Xcode will still report the above error, and PromiseKit-SwifterSwift_Privacy still exists in the project.

**Comment by MJ-BEN** [comment]
@akovalov Thank you very much, your method can effectively solve my problem.

**Comment by RomanPodymov** [comment]
Hello @MJ-BEN 
The issue [was already resolved](https://github.com/mxcl/PromiseKit/pull/1350), please try to use master instead of 8.1.2.

**Comment by MJ-BEN** [comment]
@RomanPodymov Thanks for your reply, unfortunately I can't use the master branch. According to our library management rules, I need to specify the version of each library, so I solve this problem by specifying commit now.
