### ISSUE TITLE
Swift-3.0 Branch Errors

### ISSUE THREAD

**Issue by Gerst20051** [mxcl/PromiseKit#480]
Screenshot Attached

<img width="1683" alt="screenshot 2016-07-27 12 21 01" src="https://cloud.githubusercontent.com/assets/235372/17182762/ad81c654-53f2-11e6-85db-193717a174fd.png">

**Comment by Gerst20051** [comment]
```PATCH``` should be lowercase as well as ```JSON```.

**Comment by Gerst20051** [comment]
Here is a screenshot of the remaining errors.

<img width="1671" alt="screenshot 2016-07-27 12 26 24" src="https://cloud.githubusercontent.com/assets/235372/17182918/657e11b8-53f3-11e6-98d2-39908af021f8.png">

**Comment by Gerst20051** [comment]
Resolved them by updating it to this.

```
    public class func PUT(_ URL: String, JSON: NSDictionary? = nil) -> URLDataPromise {
        return start(try OMGHTTPURLRQ.put(URL, json: JSON) as URLRequest)
    }

    public class func PATCH(URL: String, JSON: NSDictionary) -> URLDataPromise {
        return start(try OMGHTTPURLRQ.patch(URL, json: JSON) as URLRequest)
    }
```

**Comment by simonnarang** [comment]
@Gerst20051 I am still unable to import PromiseKit to my project, how did you do it?

**Comment by Gerst20051** [comment]
I am using CocoaPods.

```pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0'```

**Comment by mxcl** [comment]
Just pushed. Should be fixed, let me know if not.

**Comment by simonnarang** [comment]
@mxcl I switched over to cocoapods: `/Users/Si/Library/Developer/Xcode/DerivedData/Toast-gezugqvyoyexybguzmdcmqmarefs/Build/Products/Debug-iphonesimulator/Toast.app/Frameworks/OMGHTTPURLRQ.framework: No such file or directory`

**Comment by simonnarang** [comment]
But I get that error @mxcl

**Comment by mxcl** [comment]
Cocoapods will automatically install OMGHTTPURLRQ since it is a dependency of PromiseKit, so you're doing something wrong with CocoaPods. What commands did you run?

**Comment by simonnarang** [comment]
@mxcl I ran `pod install`
