### ISSUE TITLE
pod update fails to install PromiseKit submodules for 4.0.1

### ISSUE THREAD

**Issue by krider2010** [mxcl/PromiseKit#554]
* PromiseKit version: 4.0 (resolving to 4.0.1)
* Xcode version: 8
* CocoaPods version: 1.1.0.rc.2

`pod update` to add _PromiseKit_ fails with a submodule remote reference fail... Is this a known issue? Should I change something?

Thanks for any advice :)

```bash
Installing PromiseKit (4.0.1)

[!] Error installing PromiseKit
[!] /usr/local/bin/git submodule update --init --recursive

Submodule 'Extensions/AVFoundation' (https://github.com/PromiseKit/AVFoundation) registered for path 'Extensions/AVFoundation'
Submodule 'Extensions/Accounts' (https://github.com/PromiseKit/Accounts.git) registered for path 'Extensions/Accounts'
Submodule 'Extensions/AddressBook' (https://github.com/PromiseKit/AddressBook.git) registered for path 'Extensions/AddressBook'
Submodule 'Extensions/Alamofire' (https://github.com/PromiseKit/Alamofire) registered for path 'Extensions/Alamofire'
Submodule 'Extensions/AssetsLibrary' (https://github.com/PromiseKit/AssetsLibrary.git) registered for path 'Extensions/AssetsLibrary'
Submodule 'Extensions/Bolts' (https://github.com/PromiseKit/Bolts.git) registered for path 'Extensions/Bolts'
Submodule 'Extensions/CloudKit' (https://github.com/PromiseKit/CloudKit.git) registered for path 'Extensions/CloudKit'
Submodule 'Extensions/CoreBluetooth' (https://github.com/PromiseKit/CoreBluetooth.git) registered for path 'Extensions/CoreBluetooth'
Submodule 'Extensions/CoreLocation' (https://github.com/PromiseKit/CoreLocation.git) registered for path 'Extensions/CoreLocation'
Submodule 'Extensions/EventKit' (https://github.com/PromiseKit/EventKit.git) registered for path 'Extensions/EventKit'
Submodule 'Extensions/Foundation' (https://github.com/PromiseKit/Foundation.git) registered for path 'Extensions/Foundation'
Submodule 'Extensions/MapKit' (https://github.com/PromiseKit/MapKit.git) registered for path 'Extensions/MapKit'
Submodule 'Extensions/MessagesUI' (https://github.com/PromiseKit/MessagesUI.git) registered for path 'Extensions/MessagesUI'
Submodule 'Extensions/OMGHTTPURLRQ' (https://github.com/PromiseKit/OMGHTTPURLRQ) registered for path 'Extensions/OMGHTTPURLRQ'
Submodule 'Extensions/Photos' (https://github.com/PromiseKit/Photos.git) registered for path 'Extensions/Photos'
Submodule 'Extensions/QuartzCore' (https://github.com/PromiseKit/QuartzCore.git) registered for path 'Extensions/QuartzCore'
Submodule 'Extensions/Social' (https://github.com/PromiseKit/Social.git) registered for path 'Extensions/Social'
Submodule 'Extensions/StoreKit' (https://github.com/PromiseKit/StoreKit.git) registered for path 'Extensions/StoreKit'
Submodule 'Extensions/SystemConfiguration' (https://github.com/PromiseKit/SystemConfiguration) registered for path 'Extensions/SystemConfiguration'
Submodule 'Extensions/UIKit' (https://github.com/PromiseKit/UIKit.git) registered for path 'Extensions/UIKit'
Submodule 'Extensions/WatchConnectivity' (https://github.com/PromiseKit/WatchConnectivity.git) registered for path 'Extensions/WatchConnectivity'
Submodule path 'Extensions/AVFoundation': checked out '0456c7dea92e676473b56730097a4c2ef8cbfcd0'
Cloning into 'Extensions/AVFoundation'...
Cloning into 'Extensions/Accounts'...
error: no such remote ref 6aa7ff68fb19c20e487cff2e1edc8e1fc759cb17
Fetched in submodule path 'Extensions/Accounts', but it did not contain 6aa7ff68fb19c20e487cff2e1edc8e1fc759cb17. Direct fetching of that commit failed.```

**Comment by mxcl** [comment]
Hmm, my bad.

**Comment by krider2010** [comment]
(sorry, missed the code type off - formatted correctly now)

**Comment by mxcl** [comment]
Fixed, I believe, though CocoaPods may have cached the previous checkout so you may have some trouble.

**Comment by krider2010** [comment]
Nothing that clearing the cache (forcefully) doesn't solve 👍 

Thank you for such a speedy response. Much appreciated.
