### ISSUE TITLE
Compile error in example for retry

### ISSUE THREAD

**Issue by timbms** [mxcl/PromiseKit#776]
Example for retry on https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md 
is not compiling:
<img width="818" alt="screen shot 2018-02-14 at 19 45 05" src="https://user-images.githubusercontent.com/5411131/36221832-a86ecf9a-11bf-11e8-8cae-6a004b7a5490.png">
* PromiseKit version: 6.0
* Xcode version: 9.2

**Comment by mxcl** [comment]
Thanks for the PR~!!!!!!

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/commit/9a34665995832e942e07dc588726fbd95351fe75

**Comment by mxcl** [comment]
I fixed this and supplemented the migration guide. Thanks for the report and sorry for the omission.

**Comment by timbms** [comment]
Hi Max,

this was super quick.

I still have an issue with attempt: Still fails to compile on after

because of:

public func after(_ interval: DispatchTimeInterval) -> Guarantee<Void>


after (interval: interdelay)

->


after (interdelay)


Tim

**Comment by mxcl** [comment]
Much appreciated that you provided the error message so I wouldn't have to open a new project and compile it myself.

**Comment by mxcl** [comment]
```swift
func attempt<T>(interdelay: DispatchTimeInterval = .seconds(2), maxRepeat: Int = 3, body: @escaping () -> Promise<T>) -> Promise<T> {
    var attempts = 0
    func attempt() -> Promise<T> {
        attempts += 1
        return body().recover { error -> Promise<T> in
            guard attempts < maxRepeat else { throw error }

            return after(interdelay).then {
                attempt()
            }
        }
    }

    return attempt()
}
```

**Comment by mxcl** [comment]
K, updated.
